apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: library-system
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tmkike/ewokmacik_project
    targetRevision: main
    path: library-system/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: library-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

