apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-mongodb
  template:
    metadata:
      labels:
        app: book-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: books
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: seed
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: book-mongodb-pvc
        - name: seed
          configMap:
            name: book-mongodb-seed
