services:

  frontend:
    build:
      context: ../frontend
    container_name: library-frontend
    depends_on:
      - api-gateway
    ports:
      - "4200:80"

  api-gateway:
    image: nginx:1.27-alpine
    container_name: library-api-gateway
    depends_on:
      - book-service
      - loan-service
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro

  book-service:
    build:
      context: ./book-service
    container_name: library-book-service
    depends_on:
      - book-mongodb
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://book-mongodb:27017
      MONGODB_DB: books
      LOAN_SERVICE_URL: http://loan-service:3002
    ports:
      - "3001:3001"

  loan-service:
    build:
      context: ./loan-service
    container_name: library-loan-service
    depends_on:
      - loan-mongodb
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://loan-mongodb:27017
      MONGODB_DB: loans
      BOOK_SERVICE_URL: http://book-service:3001
    ports:
      - "3002:3002"

  book-mongodb:
    image: mongo:8
    container_name: library-book-mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./database/book-seed:/docker-entrypoint-initdb.d
      - book-mongodb-data:/data/db

  loan-mongodb:
    image: mongo:8
    container_name: library-loan-mongodb
    ports:
      - "27019:27017"
    volumes:
      - loan-mongodb-data:/data/db

volumes:
  book-mongodb-data:
  loan-mongodb-data:
